services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack-pro:latest-arm64
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=0
      - PERSISTENCE=1
      - SNAPSHOT_SAVE_STRATEGY=ON_REQUEST
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - USE_SINGLE_REGION=1
      - AWS_REGION=${AWS_REGION}
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
    stop_signal: SIGTERM
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./s3-data}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 2s
      retries: 2
      start_period: 10s
      timeout: 5s

  init-s3:
    image: amazon/aws-cli
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "aws --endpoint-url=http://localstack:4566 s3api create-bucket --bucket nexus-store &&
      aws --endpoint-url=http://localstack:4566 s3api put-bucket-acl --bucket nexus-store --acl bucket-owner-full-control &&
      aws --endpoint-url=http://localstack:4566 s3api create-bucket --bucket nexus-data &&
      aws --endpoint-url=http://localstack:4566 s3api put-bucket-acl --bucket nexus-data --acl bucket-owner-full-control &&
      echo 'S3 buckets created successfully with correct ownership'"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_REGION}
    depends_on:
      localstack:
        condition: service_healthy

  s3fs:
    build:
      context: .
      dockerfile: Dockerfile.s3fs
    privileged: true
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_URL=${AWS_S3_URL}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_MOUNTPOINT=/mnt/s3
      - AWS_REGION=${AWS_REGION}
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse"
    security_opt:
      - "apparmor:unconfined"
    volumes:
      - s3-data:/mnt/s3
    command: >
      sh -c "
        export AWS_S3_URL=${AWS_S3_URL};
        export AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME};
        export AWS_S3_MOUNTPOINT=/mnt/s3;
        echo 'Waiting for S3 bucket nexus-data to exist...';
        until aws --endpoint-url=$AWS_S3_URL s3api head-bucket --bucket $AWS_STORAGE_BUCKET_NAME; do
          echo 'Bucket not available yet... retrying in 2 seconds';
          sleep 2;
        done;
        echo 'Bucket nexus-data is now available. Mounting S3...';
        mkdir -p $AWS_S3_MOUNTPOINT;
        s3fs $AWS_STORAGE_BUCKET_NAME $AWS_S3_MOUNTPOINT -o endpoint=$AWS_S3_URL -o use_path_request_style -o nonempty;
        echo 'S3 bucket successfully mounted at $AWS_S3_MOUNTPOINT';
        tail -f /dev/null"
    depends_on:
      - localstack
      - init-s3

  nexus:
    image: sonatype/nexus3
    restart: always
    ports:
      - "8081:8081"
      - "8085:8085"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_REGION}
    volumes:
      - s3-data:/nexus-data
    depends_on:
      - localstack
      - s3fs
  # admin password: U4b&J$&TOcj8
  # GitHub user password: github123!
  # developer user password: developer123!


volumes:
  s3-data:

