services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack-pro:latest-arm64
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=0
      - PERSISTENCE=1
      - SNAPSHOT_SAVE_STRATEGY=ON_REQUEST
      - SERVICES=s3
      - DEFAULT_REGION=${AWS_REGION}
      - USE_SINGLE_REGION=1
      - AWS_REGION=${AWS_REGION}
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
    stop_signal: SIGTERM
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./s3-data}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 2s
      retries: 2
      start_period: 10s
      timeout: 5s

  init-s3:
    image: amazon/aws-cli
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "aws --endpoint-url=http://localstack:4566 s3api create-bucket --bucket ${AWS_DATA_BUCKET_NAME} &&
      aws --endpoint-url=http://localstack:4566 s3api put-bucket-acl --bucket ${AWS_DATA_BUCKET_NAME} --acl bucket-owner-full-control &&
      aws --endpoint-url=http://localstack:4566 s3api create-bucket --bucket ${AWS_STORE_BUCKET_NAME} &&
      aws --endpoint-url=http://localstack:4566 s3api put-bucket-acl --bucket ${AWS_STORE_BUCKET_NAME} --acl bucket-owner-full-control &&
      echo 'S3 buckets created successfully with correct ownership'"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_REGION}
    depends_on:
      localstack:
        condition: service_healthy

  nexus:
    image: sonatype/nexus3
    restart: always
    ports:
      - "8081:8081"
      - "8085:8085"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_REGION}
    volumes:
      - ./nexus-data:/nexus-data
    depends_on:
      - localstack
  # admin password: U4b&J$&TOcj8
  # GitHub user password: github123!
  # developer user password: developer123!


