services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=0
      - PERSISTENCE=1
      - SERVICES=s3
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./s3_data}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s

  init-s3:
    image: amazon/aws-cli
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "aws --endpoint-url=http://localstack:4566 s3api create-bucket --bucket nexus-store &&
       echo 'S3 bucket created successfully'"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      localstack:
        condition: service_healthy

  nexus:
    image: sonatype/nexus3
    restart: always
    ports:
      - "8081:8081"
      - "8085:8085"
    volumes:
      - ./nexus-data:/nexus-data
      - ./sonatype-work:/sonatype-work
    depends_on:
      - localstack
  # admin password: U4b&J$&TOcj8

